spring:
  application:
    name: candidate-evaluation-project

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/app_database?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    aws:
      credentials:
        access-key: AKIA47CRUN4Q7ZY6BTWV
        secret-key: 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
      region:
        static: us-east-1

api:
  candidate:
    evaluation:
      project:
        base:
          path: /api
          version: v1
